---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Example calculations
In this Folder you will find a sample of the key calculations done for the manuscript:"Inferring stability and persistence in the vaginal microbiome: a stochastic model of ecological dynamics"

Authors: J.M. Ponciano, Larry J. Forney, Juan P. Gomez and Jacques Ravel.

The demonstration of the concept of Stochastic Stability and how it is determined by the relationship between environmental fluctuations, the strength of density dependence and the strength of inter-specific interactions is shown in the main manuscript by Figures 1 and 2, whose code is presented in [this html file](https://jmponciano.github.io/StochasticMicrobiome/ExampleCalcs/Figures1and2.html)


All the stochastic stability calculations for our women vaginal community data sets are are in the file StochasticStability.Rmd which is knitted to the html file [StochasticStability.html](https://jmponciano.github.io/StochasticMicrobiome/ExampleCalcs/StochasticStability.html).

Figures 7 and 8 of the main manuscript are reproduced here:
[Html for figures 7 and 8](https://jmponciano.github.io/StochasticMicrobiome/ExampleCalcs/Figures7and8.html).
