---
title: "**Supporting Calculations**"
subtitle: "Inferring stability and persistence in the vaginal microbiome: A stochastic model of ecological dynamics"
author: "Jose M Ponciano, Larrry J. Forney, Juan P. Gomez, Jacques Ravel"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    toc: yes
    number_sections: true
    latex_engine: xelatex
    extra_dependencies: ["flafter","caption"]
header-includes:
  - \usepackage{placeins}
  - \usepackage{caption}
  - \renewcommand{\thefigure}{SI-\arabic{figure}}
editor_options:
  chunk_output_type: console
---

\clearpage

# Read me (begin here)

This file is the code used for a paper \textit{submitted} to \textbf{\textit{npj}}. We hope this code serve as a practical tutorial and is applied for different users in an intuitive way. Our aim is to describe a quantitative approach to fit a continuous time stochastic population dynamics model to bacterial community time series data, with the goal of estimating stochastic stability metrics for the bacterial community, as described in the main text of our manuscript \textbf{\textit{Inferring stability and persistence in the vaginal microbiome: A stochastic model of ecological dynamics}}. This code was mostly newly developed for this project.  The statistical theory used for parameter estimation was first developed in a 2014 manuscript funded by our microbiome project [Dennis & Ponciano, (2014)](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/13-1486.1). The computational methods to estimate the stochastic stability properties were originally developed in [Ives A.R., Dennis B., Cottingham K.L. and S.R. Carpenter](https://doi.org/10.1890/0012-9615(2003)073[0301:ECSAEI]2.0.CO;2), and reprogrammed in R by J.P. Gomez and J.M. Ponciano.  Simultaneously to this manuscript, J.M. Ponciano used the stochastic stability calculations of Ives et al in this exclusively computational/simulated data paper recently accepted for publication:
[Gaynor M.L., Kortessis N., Soltis D.E., Soltis P.S. and J.M. Ponciano ](https://www.journals.uchicago.edu/doi/10.1086/734411).  The application of Population Viability Monitoring ideas of [Staples *et al.*, 2005](https://conbio.onlinelibrary.wiley.com/doi/full/10.1111/j.1523-1739.2005.00283.x) to microbiome community data is new and programmed de-novo for this current manuscript.  All code presented and used here was written by J.M. Ponciano and J.P. Gomez.





